### ISSUE TITLE
Is it ready for beta?

### ISSUE THREAD

**Issue by GermanBluefox** [frankjoke/ioBroker.systeminfo#1]
The adapter looks interesting.
For which systems  is this adapter? Linux, OSX, windows, raspi, odroid, ....

and think about english docu :)

👍

**Comment by frankjoke** [comment]
It is ready from technical perspective but exactly one point is missing:  Documentation!
It works on all platform and can get information from files, system or web in json, xml and html form.
I will work on readme now in english and put a announcement in german into forum.

**Comment by frankjoke** [comment]
Hi BlueFox! I made it now a public beta and it is also on NPM already.
