### ISSUE TITLE
Do not use adapter.objects

### ISSUE THREAD

**Issue by foxriver76** [frankjoke/ioBroker.systeminfo#18]
- see https://github.com/ioBroker/ioBroker.js-controller/issues/359
Occurs in:
- https://github.com/frankjoke/ioBroker.systeminfo/blob/c83ca4e9d348a03603dc0f56e1bf6f9b27b5e24e/myAdapter.js#L44
- https://github.com/frankjoke/ioBroker.systeminfo/blob/c83ca4e9d348a03603dc0f56e1bf6f9b27b5e24e/myAdapter.js#L219

js-controller provides methods for `adapter.getObjectView` and `adapter.getObjectList` if you need additional methods, let me know.

**Comment by Berchemer** [comment]
Warning Message in LOG:
adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!

**Comment by frankjoke** [comment]
Ich weiß das schon, es gibt auch eine neue Version von myAdapter welche ich noch nicht mit diesem Adapter getestet habe da ich den Adapter zur Zeit komplett umfunktioniere und er vielleicht mit neuem Namen wiederkommt.

Werde aber bis der js-controller nicht nur warnt sondern nicht mehr funktioniert ein update erstellen.
