### ISSUE TITLE
adapter.objects.getObjectList is deprecated

### ISSUE THREAD

**Issue by darkiop** [frankjoke/ioBroker.systeminfo#21]
`2020-06-23 08:45:54.651  - warn: systeminfo.0 (14021) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!
2020-06-23 08:45:56.359  - warn: systeminfo.0 (14021) Used invalid characters: systeminfo.0.System.Software.? changed to systeminfo.0.System.Software._`

**Comment by frankjoke** [comment]
This is a known issue and will be corrected before js-controller will handle it that way (currently just a warning).
